//@version=6

//indicator("Simple MA Crossover", overlay=true)
strategy("EA", overlay=true, fill_orders_on_standard_ohlc = true)


random_time = input(false)
stop_losses = input(false)
take_profit = input(false)
paper_trade_test = input(false)

identifier = input(12345)
stop_in_points = input(50)
take_profit_in_points = input(200)
lot_size = input(.1)
moving_average = input(21, title="Fast MA Period")
quantity = input(1.0)
moving_average_type = input('SMA')
time_frame = input(60)

ma_fast = input(21)
ma_slow = input(89)

plot(ta.sma(close, ma_fast), title="50 SMA", color=#00DB00, linewidth=1)
plot(ta.sma(close, ma_slow), title="100 SMA", color=#FC8A10, linewidth=1)

longCondition = ta.crossover(ta.sma(close, ma_fast), ta.sma(close, ma_slow))
shortCondition = ta.crossunder(ta.sma(close, ma_fast), ta.sma(close, ma_slow))
if(longCondition)
    strategy.entry('long', strategy.long, qty = quantity)
if(shortCondition)
    strategy.entry('short', strategy.short, qty = quantity)




